# This is a basic workflow to help you get started with Actions

name: 'weather bot'

# Controls when the workflow will run
on:
  push:
  schedule:
    - cron: '0 21 * * *'

jobs:
  weatherbot:
    runs-on: ubuntu-latest

    steps:
      # 首先copy git仓库到虚拟机上
      - name: 'check codes'
        uses: actions/checkout@v3

      # 执行仓库中的脚本文件
      - name: get weather
        run: bash ./weather.sh

      # 获取格式化的日期并存入github内置的环境变量中
      - name: get date
        run: |
          echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
       
      # 使用现成的发送邮箱的github action来发送邮件
      - name: Send mail
        uses: dawidd6/action-send-mail@master
        with:
          # 这些是发送邮件需要配置的参数，更多详细的说明请访问具体的仓库
          server_address: smtp.qq.com
          server_port: 465
          # 这些sectret的环境变量需要配置在setting中的secret下
          username: ${<!-- -->{<!-- --> secrets.MAIL_USERNAME }}
          password: ${<!-- -->{<!-- --> secrets.MAIL_PASSWORD }}
          subject: 天气预报 (${<!-- -->{<!-- -->env.REPORT_DATE}})
          body: file://result.html
          to: ww-1096@163.com
          from: GitHub Actions
          content_type: text/html
